In [32]:
import pandas as pd
path =os.path.join('/data/yongchan/zero-shot-domain-specific-whisper/preprocessed_data/ACTER/en/htfl/annotated/annotations/sequential_annotations/iob_annotations/with_named_entities/htfl_en_001_seq_terms_nes.tsv')
lines = pd.read_csv(path,  sep='\t', skip_blank_lines=False, names=['word', 'boi'])
domain_terms = []
domain_term = []

for i in range(len(lines)):
    candidate_word = lines.iloc[i]['word']
    boi = lines.iloc[i]['boi']
    if boi == 'B':
        domain_term.append(candidate_word)
    elif boi == 'I':
        domain_term.append(candidate_word)
    else:
        if len(domain_term) > 0:
            domain_terms.append(domain_term)
            domain_term = []
            
if len(domain_term) > 0:
    domain_terms.append(domain_term)
    domain_term = []
            
        
print(domain_terms)

[['patient'], ['conditions'], ['patient'], ['Medicare', 'Patient', 'Safety', 'Monitoring', 'System'], ['MPSMS'], ['adverse', 'event'], ['patients', 'hospitalized'], ['acute', 'myocardial', 'infarction'], ['congestive', 'heart', 'failure'], ['pneumonia'], ['conditions'], ['surgery'], ['patients'], ['hospitals'], ['significant'], ['adverse', 'event'], ['acute', 'myocardial', 'infarction'], ['congestive', 'heart', 'failure'], ['in-hospital', 'adverse', 'events'], ['patients'], ['pneumonia'], ['surgical', 'conditions'], ['pressure', 'ulcers'], ['surgical', 'patients'], ['patient']]

# Create dataset with longer text

In [2]:
import os
import re
import numpy as np
import pandas as pd
from IPython.core.debugger import set_trace

train_dataset = pd.DataFrame(columns=['text', 'label', 'unique_label'])
master_path = '/data/yongchan/ATE/ACTER/en'

def normalize_texts(texts):
    text = ' '.join(texts)
    # Remove any empty space that are placed before special characters
    text = re.sub(r'\s+(?=[\W_])', '', text)
    
    # Remove any empty space that are placed after the character /
    text = re.sub(r'/(?=\s)', '/', text)
    return text

for dataset_name in os.listdir(master_path):
    rows = {}
    all_domain_terms = []
    all_texts = []
    all_term_types = []
    dataset_path = os.path.join(master_path, dataset_name, 'annotated')
    
    if dataset_name == 'cor':
        continue
    
    for category in os.listdir(dataset_path):
        category_path = os.path.join(dataset_path, category)
        if category == 'annotations':
            for seq_annotation in os.listdir(category_path):
                if seq_annotation == 'sequential_annotations':
                    iob_annotation_path = os.path.join(category_path, seq_annotation, 'iob_annotations', 'with_named_entities')
                    for filename in sorted(os.listdir(iob_annotation_path), key=lambda x: int(os.path.splitext(x)[0].split('_')[2])):
                        file_path = os.path.join(iob_annotation_path, filename)
                        lines = pd.read_csv(file_path,  sep='\t', names=['word', 'boi'])
                        domain_terms = []
                        domain_term = []
                        for i in range(len(lines)):
                            candidate_word = lines.iloc[i]['word']                                  
                            boi = lines.iloc[i]['boi']
                            
                            if candidate_word is np.nan and boi is not np.nan:
                                candidate_word = 'None'
                                
                            if boi == 'B':
                                if len(domain_term) == 0:
                                    domain_term.append(candidate_word)
                                else:
                                    domain_term = normalize_texts(domain_term)
                                    domain_terms.append(domain_term)
                                    domain_term = [candidate_word]
                            elif boi == 'I':
                                domain_term.append(candidate_word)
                            else:
                                if len(domain_term) > 0:
                                    domain_term = normalize_texts(domain_term)
                                    domain_terms.append(domain_term)
                                    domain_term = []
                                    
                        if len(domain_term) > 0:
                            domain_term = normalize_texts(domain_term)
                            domain_terms.append(domain_term)
                            domain_term = []
                        all_domain_terms.append(domain_terms)
                        
                elif seq_annotation == 'unique_annotation_lists':
                    unique_annotation_list_path = os.path.join(category_path, seq_annotation, f"{dataset_name}_en_terms_nes.tsv")
                    lines = pd.read_csv(unique_annotation_list_path,  sep='\t', names=['word', 'term_type'])
                    for i, domain_terms in enumerate(all_domain_terms):
                        term_types = []
                        for domain_term in domain_terms:
                            domain_term = domain_term.lower()
                            term_type = ''
                            count = 0
                            while len(term_type) == 0:                                    
                                if count==0:
                                    term_type = lines[lines['word']==domain_term]['term_type']
                                
                                elif count==1:
                                    character_removed_domain_term_wo_ws = re.sub(r'[^a-zA-Z0-9\s]', '', domain_term)
                                    term_type = lines[lines['word']==character_removed_domain_term_wo_ws]['term_type']
                                    
                                elif count==2:
                                    character_removed_domain_term_w_ws = re.sub(r'[^a-zA-Z0-9\s]', ' ', domain_term).split(' ')
                                    for i in sorted(range(len(character_removed_domain_term_w_ws)), reverse=True):
                                        for j in range(len(character_removed_domain_term_w_ws)):
                                            sliced_dash_removed_domain_term_w_ws = ' '.join(character_removed_domain_term_w_ws[j:j+i])
                                            term_type = lines[lines['word'].str.contains(sliced_dash_removed_domain_term_w_ws)]['term_type']
                                            if len(term_type) > 0:
                                                break
                                        if len(term_type) > 0:
                                            break
                                
                                elif count > 2:
                                    term_type = 'Not Annotated'                                            
                                    print(f'Path: {unique_annotation_list_path}, domain_term: {domain_term}, index: {i}')
                                    break
                                    
                                count += 1                                    

                            if not isinstance(term_type, str):
                                term_type = term_type.astype(str).values[0]
                            term_types.append(term_type)
                        all_term_types.append(term_types)
                                
        elif category == 'texts':
            for filename in sorted(os.listdir(category_path), key=lambda x: int(os.path.splitext(x)[0].split('_')[2])):
                with open(os.path.join(category_path, filename), 'r') as f:
                    text = f.read()
                    all_texts.append(text)
    
    rows = {'text': all_texts, 'label': all_domain_terms, 'unique_label': all_term_types}
    if dataset_name == 'htfl':
        rows['domain'] = ['Heart Failure']*len(all_texts)
        test_dataset = pd.DataFrame(rows)
    elif dataset_name == 'equi':
        rows['domain'] = ['Equitation']*len(all_texts)
        validation_dataset = pd.DataFrame(rows)
    else:
        dataset_name_to_domain = {'corp': 'Corruption', 'wind': 'Wind Energy'}
        rows['domain'] = [dataset_name_to_domain[dataset_name]]*len(all_texts)
        train_dataset = pd.concat([train_dataset, pd.DataFrame(rows)])

In [3]:
print(f'Train dataset length: {len(train_dataset)}')
print(f'Validation dataset length: {len(validation_dataset)}')
print(f'Test dataset length: {len(test_dataset)}')

Train dataset length: 17
Validation dataset length: 34
Test dataset length: 190

In [4]:
pd.set_option('display.max_colwidth', 500)

test_dataset.head(10)

,text,label,unique_label,domain
0,"National trends in patient safety for four common conditions, 2005-2011.\nThe effects of more than a decade of national efforts dedicated to improve patient safety remain largely unclear. This study used the Medicare Patient Safety Monitoring System (MPSMS) database to assess national trends in adverse event rates between 2005 through 2011 for patients hospitalized with acute myocardial infarction, congestive heart failure, pneumonia, or conditions requiring surgery. The analysis included a ...","[patient, conditions, patient, Medicare Patient Safety Monitoring System, MPSMS, adverse event, patients, hospitalized, acute myocardial infarction, congestive heart failure, pneumonia, conditions, surgery, patients, hospitals, significant, adverse event, acute myocardial infarction, congestive heart failure, in-hospital, adverse events, patients, pneumonia, surgical, conditions, pressure ulcers, surgical, patients, patient]","[Common_Term, Common_Term, Common_Term, Named_Entity, Named_Entity, Specific_Term, Common_Term, Common_Term, Specific_Term, Specific_Term, Common_Term, Common_Term, Common_Term, Common_Term, Common_Term, OOD_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term, Specific_Term, Common_Term, Common_Term, Common_Term, Common_Term, Specific_Term, Common_Term, Common_Term, Common_Term]",Heart Failure
1,Cross-talk between the heart and adipose tissue in cachectic heart failure patients with respect to alterations in body composition: a prospective study.\nOBJECTIVES:\nCardiac cachexia (CC) is associated with changes in body composition. Lipolysis and increased energy expenditure caused by A- and B natriuretic peptides (NPs) have been suggested to play a role in CC. We tested the hypothesis that neurohormones and adipokines are associated with body composition in CC and that a progressive lo...,"[Cross-talk, heart, adipose tissue, cachectic heart failure, patients, prospective study, Cardiac cachexia, CC, Lipolysis, A-, B natriuretic peptides, NPs, CC, neurohormones, adipokines, CC, fat free mass, FFM, fat mass, FM, FFM, FM, dual energy X-ray absorptiometry, DXA, non-diabetic, patients, chronic heart failure, CHF, CC, non-cachectic CHF, myocardial infarction-both, Biomarkers, neurohormonal stimulation, inflammation, endothelial dysfunction, N-terminal proBNP, NT-proBNP, midregional ...","[Specific_Term, Common_Term, Specific_Term, Specific_Term, Common_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term, Common_Term, Common_Term, Common_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term,...",Heart Failure
2,"Diagnosis of heart failure with preserved ejection fraction: role of clinical Doppler echocardiography.\nIn developed countries, at least 38–54% of patients with heart failure show preserved left ventricular (LV) ejection fraction. The prevalence of heart failure with preserved ejection fraction (HFPEF) is steadily increasing and its prognosis is poor. LV diastolic dysfunction, either alone or in combination with other factors (figure 1), is the major underlying mechanism of HFPEF. In the ge...","[Diagnosis, heart failure with preserved ejection fraction, clinical, Doppler echocardiography, patients, heart failure, preserved left ventricular, LV, ejection fraction, prevalence, heart failure with preserved ejection fraction, HFPEF, prognosis, LV diastolic dysfunction, HFPEF, clinical, diastolic dysfunction, mortality, diagnosis, clinical, prognostic, diastolic dysfunction, HFPEF, European Society of Cardiology, HFPEF, symptoms, heart failure, preserved LV ejection fraction, non-dilate...","[Common_Term, Specific_Term, Common_Term, Specific_Term, Common_Term, Common_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term, Specific_Term, Specific_Term, Common_Term, Specific_Term, Specific_Term, Common_Term, Specific_Term, Common_Term, Common_Term, Common_Term, Common_Term, Specific_Term, Specific_Term, Named_Entity, Specific_Term, Common_Term, Common_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Ter...",Heart Failure
3,Treatment of anemia in patients with heart disease: a clinical practice guideline from the American College of Physicians.\nDescription: The American College of Physicians (ACP) developed this guideline to present the evidence and provide clinical recommendations on the treatment of anemia and iron deficiency in adult patients with heart disease.\n\nMethods: This guideline is based on published literature in the English language on anemia and iron deficiency from 1947 to July 2012 that was i...,"[anemia, patients, heart disease, clinical practice guideline, American College of Physicians, American College of Physicians, ACP, clinical, anemia, patients, heart disease, anemia, MEDLINE, Cochrane Library, Outcomes, mortality, hospitalization, exercise tolerance, quality of life, cardiovascular events, myocardial infarction, congestive heart failure, arrhythmia, cardiac death, hypertension, venous thromboembolic events, ischemic cerebrovascular events, clinicians, patient, anemic, patien...","[Specific_Term, Common_Term, Common_Term, Specific_Term, Named_Entity, Named_Entity, Named_Entity, Common_Term, Specific_Term, Common_Term, Common_Term, Specific_Term, Named_Entity, Named_Entity, Common_Term, Common_Term, Common_Term, Specific_Term, Common_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term, Common_Term, Specific_Term, Common_Term, Common_Term, Named_Entity, Specific_Term, Named_Entity, Spe...",Heart Failure
4,"Treatment of anemia in patients with heart disease: a systematic review.\nBackground: The benefits of anemia treatment in patients with heart disease are uncertain.\n\nPurpose: To evaluate the benefits and harms of treatments for anemia in adults with heart disease.\n\nData Sources: MEDLINE, EMBASE, and Cochrane databases; clinical trial registries; reference lists; and technical advisors.\n\nStudy Selection: English-language trials of blood transfusions, iron, or erythropoiesis-stimulating ...","[anemia, patients, heart disease, anemia, patients, heart disease, anemia, heart disease, MEDLINE, EMBASE, Cochrane, clinical, blood transfusions, erythropoiesis-stimulating agents, anemia, congestive heart failure, coronary heart disease, transfusion, hemoglobin, health, outcomes, transfusion, mortality, relative risk, CI, mortality, patients, acute coronary syndrome, P, intravenous, exercise tolerance, quality of life, patients, heart failure, erythropoiesis-stimulating agent, therapy, ven...","[Specific_Term, Common_Term, Common_Term, Specific_Term, Common_Term, Common_Term, Specific_Term, Common_Term, Named_Entity, Named_Entity, Named_Entity, Common_Term, Common_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term, Specific_Term, Common_Term, Common_Term, Common_Term, Common_Term, Specific_Term, OOD_Term, Common_Term, Common_Term, Specific_Term, OOD_Term, Specific_Term, Specific_Term, Common_Term, Common_Term, Common_Term, Specific_Term, Common_Term, Spec...",Heart Failure
5,"Remote ischemic conditioning for patients with heart failure?\nManagement of patients with heart failure (HF), stemming from ischemic and nonischemic cardiomyopathies, continues to be problematic, despite the inroads made in the pharmacological armamentarium, by implantable cardioverter defibrillators, cardiac resynchronization therapy, and the eventual resort to cardiac transplantation, and left and/or right ventricular assist devices. Both patients with low left ventricular ejection fracti...","[Remote ischemic conditioning, patients, heart failure, patients, heart failure, HF, ischemic, nonischemic cardiomyopathies, pharmacological, implantable cardioverter defibrillators, cardiac resynchronization therapy, cardiac transplantation, left, right ventricular assist devices, patients, left ventricular ejection fraction, patients, HF, preserved left ventricular ejection fraction, hospital, physicians, acute, outpatient, epidemic, medical]","[Specific_Term, Common_Term, Common_Term, Common_Term, Common_Term, Common_Term, Specific_Term, Specific_Term, Common_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term, Specific_Term, Common_Term, Common_Term, Specific_Term, Common_Term, Common_Term, Common_Term, Common_Term, Common_Term, Common_Term]",Heart Failure
6,"Comments on ""the role of the emergency department in acute heart failure clinical trials-Enriching patient identification and enrollment"" by Collins et al.\nAs the authors suggest, patient categorization in the emergency department is perhaps the single most important component that is not focused on in modern acute heart failure (AHF) clinical studies. However, patients with AHF are highly heterogeneous, and appropriate risk stratification is essential in conducting studies in this area.","[emergency department, acute heart failure, clinical, patient, Collins, patient, emergency department, acute heart failure, AHF, clinical, patients, AHF, risk stratification]","[Common_Term, Common_Term, Common_Term, Common_Term, Named_Entity, Common_Term, Common_Term, Common_Term, Common_Term, Common_Term, Common_Term, Common_Term, Specific_Term]",Heart Failure
7,"Predictors of mortality in patients with an implantable cardiac defibrillator: a systematic review and meta-analysis.\nBACKGROUND:\nMany current predictors of mortality in heart failure (HF) were evaluated before the use of implantable cardioverter defibrillators (ICDs). We conducted a meta-analysis to identify factors associated with mortality in ICD-HF patients.\nMETHODS:\nWe searched in MedLine, EMBASE, and CINAHL in May 2012. Two reviewers selected citations that included ambulatory ICD ...","[mortality, patients, implantable cardiac defibrillator, meta-analysis, mortality, heart failure, HF, implantable cardioverter defibrillators, ICDs, meta-analysis, mortality, ICD-HF, patients, MedLine, EMBASE, CINAHL, ambulatory, ICD, patients, mortality, multivariable regression, meta-analyzed, mortality, random-effects models, ICD, patients, hazard ratio, HR, confidence interval, CI, baseline, glomerular filtration rate, HR, CI, chronic obstructive pulmonary disease, HR, CI, diabetes, HR, ...","[Common_Term, Common_Term, Specific_Term, OOD_Term, Common_Term, Common_Term, Common_Term, Specific_Term, Specific_Term, OOD_Term, Common_Term, Specific_Term, Common_Term, Named_Entity, Named_Entity, Named_Entity, Specific_Term, Specific_Term, Common_Term, Common_Term, OOD_Term, OOD_Term, Common_Term, OOD_Term, Specific_Term, Common_Term, Specific_Term, Specific_Term, OOD_Term, OOD_Term, Specific_Term, Specific_Term, Specific_Term, OOD_Term, Specific_Term, Specific_Term, OOD_Term, Common_Ter...",Heart Failure
8,"Low-dose dopamine or low-dose nesiritide in acute heart failure with renal dysfunction: the ROSE acute heart failure randomized trial.\nIMPORTANCE:\nSmall studies suggest that low-dose dopamine or low-dose nesiritide may enhance decongestion and preserve renal function in patients with acute heart failure and renal dysfunction; however, neither strategy has been rigorously tested.\nOBJECTIVE:\nTo test the 2 independent hypotheses that, compared with placebo, addition of low-dose dopamine (2 ...","[dopamine, nesiritide, acute heart failure, renal dysfunction, ROSE, acute heart failure, randomized, dopamine, nesiritide, renal function, patients, acute heart failure, renal dysfunction, placebo, dopamine, nesiritide, bolus, diuretic, therapy, renal function, patients, acute heart failure, renal dysfunction, double-blind, placebo-controlled, clinical, Renal Optimization Strategies Evaluation, ROSE, hospitalized, patients, acute heart failure, renal dysfunction, estimated glomerular filtra...","[Specific_Term, Specific_Term, Common_Term, Specific_Term, Named_Entity, Common_Term, OOD_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term, Common_Term, Specific_Term, Common_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term, Specific_Term, Common_Term, Common_Term, Specific_Term, OOD_Term, Common_Term, Common_Term, Named_Entity, Named_Entity, Common_Term, Common_Term, Common_Term, Specific_Term, Specific_Term, OOD_Term, Common_Term, Named_Entity, OO...",Heart Failure
9,"Participating in a multihospital study to promote adoption of heart failure guidelines: lessons for nurse leaders.\nMany multisite studies in practice settings focus on improving processes of care, adopting evidence-based practices, and improving patient outcomes. While specific research questions may be the focus, it is the implementation issues and strategies that reveal how individuals and organizations are profoundly transformed. Utilizing voluntary testimonies and conversations with par...","[heart failure, nurse, evidence-based, patient, outcomes, nurses, Magnet(®)]","[Common_Term, Common_Term, Specific_Term, Common_Term, Common_Term, Common_Term, Named_Entity]",Heart Failure

In [5]:
from datasets import Dataset, DatasetDict

train_dataset = Dataset.from_pandas(train_dataset, preserve_index=False)
test_dataset = Dataset.from_pandas(test_dataset, preserve_index=False)
validation_dataset = Dataset.from_pandas(validation_dataset, preserve_index=False)

In [6]:
train_dataset['label']

[['HORIZONTAL-AXIS WIND TURBINE BLADES',
  'GRADUATE SCHOOL OF NATURAL AND APPLIED SCIENCES',
  'MIDDLE EAST TECHNICAL UNIVERSITY',
  'SERHAT DURAN',
  'MECHANICAL',
  'ENGINEERING',
  'Graduate School of Natural and Applied Sciences',
  'Canan ÖZGEN',
  'Kemal IDER',
  'Tahsin ÇETINKAYA',
  'O. Cahit ERALP',
  'Kahraman ALBAYRAK',
  'Cemil YAMALI',
  'Kahraman ALBAYRAK',
  'Tahsin ÇETINKAYA',
  'Sinan AKMANDOR',
  'Serhat DURAN',
  'HORIZONTAL-AXIS WIND TURBINE BLADES',
  'Duran',
  'Serhat',
  'Mechanical',
  'Engineering',
  'Kahraman ALBAYRAK',
  'Tahsin ÇETINKAYA',
  'horizontal-axis wind turbine',
  'HAWT',
  'blades',
  'aerodynamic forces',
  'blades',
  'HAWT blade design',
  'aerodynamic',
  'aerodynamic',
  'HAWTs',
  'Blade-element momentum theory',
  'BEM',
  'strip theory',
  'aerodynamic',
  'HAWT blades',
  'HAWT blade design',
  'blade design',
  'rotor',
  'BEM theory',
  'blade shape',
  'blade',
  'loaded',
  'loaded',
  'blade',
  'power prediction',
  'blade',
  'blade shape',
  'power',
  'wind',
  'blade',
  'power',
  'BLADESIGN',
  'HAWT blade design',
  'blade geometry',
  'chord-length',
  'twist distributions',
  'tip-speed ratio',
  'power coefficient',
  'rotor diameter',
  'power',
  'turbine',
  'blades',
  'wind velocity',
  'blade profile',
  'airfoil',
  'blade design',
  'Horizontal-Axis Wind Turbine Blades',
  'Wind energy',
  'Aerodynamics',
  'Airfoil',
  'Duran',
  'Serhat',
  'Kahraman ALBAYRAK',
  'Tahsin ÇETINKAYA',
  'BLADESIGN',
  'airfoil',
  'Kahraman Albayrak',
  'Tahsin Çetinkaya',
  'ASELSAN Inc.',
  'Windmills',
  'Technological',
  'Wind Turbines',
  '2.HORIZONTAL-AXIS WIND TURBINES',
  'Horizontal-Axis Wind Turbine',
  'Horizontal-Axis Wind Turbines',
  'rotor',
  'power-train',
  'nacelle',
  'tower',
  'foundation',
  'electrical',
  'Aerodynamic',
  'HAWTs',
  'HAWTs',
  'HAWTs',
  'HAWT',
  '3.AERODYNAMICS',
  'HAWTs',
  'Actuator Disk Theory',
  'Betz Limit',
  'General Momentum Theory',
  'Blade Element Theory',
  'Blade Element-Momentum',
  'BEM',
  'Theory',
  'Vortex Theory',
  '4.HAWT BLADE DESIGN',
  'Tip-Loss Factor',
  'HAWT',
  'Flow States',
  'Airfoil',
  'HAWT Blade Design',
  'Blade Design',
  'Blade Geometry',
  'Chord-Length Distribution',
  'Twist Distribution',
  'Power Prediction',
  'Blade Shape',
  'BLADE DESIGN',
  'XFOILP4',
  'BLADESIGN',
  'Blade Design',
  'BLADESIGN',
  'windmill',
  'Savonius rotor',
  'Darrieus rotor',
  'horizontal-axis wind turbines',
  'Enfield-Andreau turbine',
  'flow path',
  'Upwind',
  'rigid hub',
  'three-bladed',
  'downwind',
  'teetered',
  'two-bladed turbine',
  'horizontal-axis wind turbine',
  'HAWT',
  'Upwind rotor',
  'Downwind rotor',
  'rotor power coefficient',
  'tip-speed ratio',
  'HAWT',
  'fixed blade pitch',
  'flow',
  'wind turbine',
  'non-rotating',
  'actuator disk',
  'Velocity',
  'pressure distribution',
  'streamtube',
  'Betz turbine',
  'Streamtube',
  'flow',
  'rotating',
  'wind turbine blade',
  'streamtube',
  'flow',
  'HAWT rotor',
  'HAWTs',
  'power coefficients',
  'tip-speed ratio',
  'HAWT',
  'wake rotation',
  'blade elements',
  'Blade geometry',
  'HAWT',
  'Tip',
  'root',
  'vortices',
  'bound circulation',
  'blade length',
  'vortices',
  'axial',
  'vortex lines',
  'axial induction factor',
  'flow state',
  'thrust',
  'rotor',
  'elemental power coefficient',
  'relative wind angles',
  'tip-speed ratio',
  'relative wind angle',
  'tip-speed ratio',
  'elemental power coefficient',
  'glide ratios',
  'Chord-length distribution',
  'blade',
  'Twist distribution',
  'blade',
  'power coefficient',
  'tip-speed ratio',
  'blade chord-length variation',
  'nondimensionalized blade radius',
  'twist distribution',
  'blade radius',
  'power coefficient',
  'blade',
  'blades',
  'peak performance',
  'wind turbines',
  'Drag/ Lift ratio',
  'peak performance',
  'three-bladed wind turbine',
  'drag',
  'tip losses',
  'relative wind angle',
  'Relative wind angle',
  'three-bladed wind turbines',
  'Blade chord length distribution',
  'three-bladed wind turbines',
  'Twist angle distribution',
  'chord-length',
  'blade',
  'Chord-length distribution',
  'blade',
  'tip-speed ratio',
  'Twist distribution',
  'twist',
  'blade',
  'Distribution of angle of attack',
  'twist',
  'blade',
  'Distribution of angle of attack',
  'twist',
  'chord-length',
  'blade',
  'power coefficients',
  'blades',
  'blade',
  'Radial thrust coefficient',
  'blade',
  'Radial thrust coefficient',
  'twist',
  'chord-length',
  'blade',
  'Working range',
  'blade',
  'Working range',
  'twist',
  'chord-length',
  'blade',
  'Reynolds number',
  'peak performance',
  'three-bladed turbine',
  'blade elements',
  'root',
  'tip',
  'blade',
  'blade elements',
  'root',
  'tip',
  'blade',
  'Isometric',
  'blade elements',
  'blade',
  'Isometric',
  'blade elements',
  'blade',
  'blade',
  'blade',
  'XFOIL',
  'lift coefficient',
  'XFOIL',
  'drag coefficient',
  'BLADESIGN',
  'Flow',
  'HAWT Blade Design',
  'power coefficient',
  'blade',
  'blade',
  'chord-length distribution',
  'blade',
  'blade',
  'blade',
  'blade design',
  'Technical wind energy potential',
  'installed capacities',
  'wind turbines',
  'Power coefficient',
  'tip-speed ratio',
  '4.1Blade chord',
  'twist distribution',
  'three-bladed HAWT',
  'Power production',
  'fixed rotational three-bladed HAWT',
  'blade',
  'Blade geometry',
  'blade',
  'airfoils',
  'rotor diameters',
  'turbine power outputs',
  'CP',
  'power coefficient',
  'wind turbine rotor',
  'rotor power coefficient',
  'thrust coefficient',
  'wind turbine rotor',
  'thrust coefficient',
  'annular rotor section',
  'power output',
  'wind turbine rotor',
  'air mass flow rate',
  'rotor plane',
  'free stream velocity of wind',
  'relative wind velocity',
  'wind velocity',
  'rotor plane',
  'wind velocity',
  'far wake',
  'axial wind velocity',
  'rotor plane',
  'radial wind velocity',
  'rotor plane',
  'angular wind velocity',
  'rotor plane',
  'induced angular velocity',
  'bound vorticity',
  'rotor blades',
  'axial wind velocity',
  'far wake',
  'radial wind velocity',
  'far wake',
  'angular wind velocity',
  'far wake',
  'wind turbine rotor',
  'radius',
  'wind turbine rotor',
  'radial coordinate',
  'rotor plane',
  'radial coordinate',
  'far wake',
  'rotor radius',
  'hub',
  'blade',
  'blade radius',
  'blade element',
  'CP',
  'upwind pressure',
  'rotor',
  'downwind pressure',
  'rotor',
  'pressure drop',
  'rotor plane',
  'far wake',
  "Bernoulli's constant",
  'free-stream',
  'inflow',
  "Bernoulli's constant",
  'outflow',
  'far wake',
  'rotor thrust',
  'rotor torque',
  'drag force',
  'annular blade element',
  'lift force',
  'annular blade element',
  'rotor',
  'drag coefficient',
  'airfoil',
  'lift coefficient',
  'airfoil',
  'lift coefficient',
  'airfoil',
  'tip-loss factor',
  'tip-loss factor',
  'blade element',
  'blade elements',
  'blades',
  'rotor',
  'axial induction factor',
  'rotor plane',
  'axial induction factor',
  'far wake',
  'angular induction factor',
  'tip-speed ratio',
  'rotor',
  'tip-speed ratio',
  'tip-speed ratio',
  'tip-speed ratio',
  'blade element',
  'tip-speed ratio',
  'hub',
  'axial induction factor',
  'axial induction factor',
  'blade chord length',
  'blade chord length',
  'blade element',
  'air density',
  'angular velocity of wind turbine rotor',
  'angle of attack',
  'angle of attack',
  'pitch angle',
  'blade setting angle',
  'pitch angle',
  'blade element',
  'relative wind velocity',
  'rotor plane',
  'relative wind angle',
  'relative wind angle',
  'blade element',
  'solidity ratio',
  'kinematic viscosity of air',
  'glide ratio',
  'blade length',
  'blade length',
  'Reynolds number',
  'horizontal-axis wind turbine',
  'vertical-axis wind turbine',
  'blade element-momentum theory',
  'tip-speed ratio',
  'HAWT',
  'VAWT',
  'BEM',
  'TSR',
  'MATLAB\uf6da',
  'HAWT blade design',
  'power performance prediction',
  'Blade-Element Momentum',
  'BEM',
  'theory',
  'horizontal-axis wind turbine blades',
  'power',
  'wind turbine rotor',
  'blades',
  'rotor',
  'wind speed',
  'airfoil',
  'airfoil',
  'blade geometry',
  'twist',
  'chord-length',
  'blade',
  'blade',
  'rotor diameter',
  'power',
  'blades',
  'horizontal-axis wind turbines',
  'wind turbines',
  'horizontal-axis',
  'vertical-axis wind turbines',
  'wind turbine',
  'wind turbines',
  'horizontal-axis wind turbines',
  'wind turbines',
  'technological',
  'horizontal-axis wind turbines',
  'horizontal-axis wind turbines',
  'horizontal-axis wind turbines',
  'horizontal-axis wind turbines',
  'horizontal-axis wind turbines',
  'aerodynamic',
  'horizontal-axis wind turbines',
  'horizontal-axis wind turbine',
  'rotor',
  'aerodynamic',
  'horizontal-axis wind turbines',
  'aerodynamic',
  'horizontal-axis wind turbines',
  'HAWT blade design',
  'BEM theory',
  'BEM theory',
  'tip-losses',
  'thrust coefficient',
  'airfoil',
  'HAWT blade design',
  'airfoil',
  'blade',
  'blade',
  'relative wind angle',
  'tip-speed ratio',
  'blade',
  'chord-length distribution',
  'blade',
  'twist distribution',
  'blade',
  'blade',
  'blade',
  'blade design',
  'HAWT',
  'Reynolds number',
  'blades',
  'XFOIL',
  'airfoil',
  'HAWT blade design',
  'BLADESIGN',
  'MATLAB\uf6da',
  'blade design',
  'WINDMILLS',
  'technology',
  'wind turbine',
  'wind machine',
  'windmill',
  'electricity',
  'wind machine',
  'windmill',
  'windmill',
  'mechanical power',
  'wind power',
  'East India',
  'Tibet',
  'Persia',
  'Afghanistan',
  'wind power',
  'Iskenderiye',
  'windmill',
  'Near East',
  'Central Asia',
  'windmill',
  'windmill',
  'Persia',
  'Eastern Persia',
  'Afghanistan',
  'windmill',
  'vertical-axis',
  'drag type',
  'windmill',
  'vertical-axis windmills',
  'Far East',
  'vertical-axis windmills',
  'sails',
  'millstones',
  'driver',
  'rotor',
  'wind speeds',
  'windmill',
  'vertical-axis Persian windmills',
  'Europe',
  'horizontal-axis windmill',
  'technical',
  'wind turbine',
  'vertical-axis windmills',
  'horizontal-axis windmills',
  'EbulIz',
  'Artuk Turks',
  'Diyarbakır',
  'Northwest Europe',
  'France',
  'Germany',
  'Great Britain',
  'Iberia',
  'Low Countries',
  'windmill',
  'shaft',
  'sails',
  'Persian mill',
  'horizontal-axis European windmills',
  'mechanical',
  'sails',
  'horizontal-axis windmill',
  'mechanism',
  'vertical-axis windmill',
  'engineering',
  'transmission of power',
  'horizontal rotor shaft',
  'shaft',
  'grindstones',
  'mill',
  'wind',
  'rotor',
  'horizontal-axis windmill',
  'windmills',
  'horizontal-axis windmills',
  'vertical-axis',
  'right angle gear mechanism',
  'rotor axis',
  'sails',
  'wind',
  'sail',
  'wind',
  'sail',
  'wind',
  'engineering',
  'aerodynamics',
  'windmills',
  'mechanical power',
  'wind turbines',
  'electrical energy',
  'wind',
  'electric generation',
  'mechanical power',
  'wind generators',
  'turbines',
  'wind turbine',
  'wind turbine rotor',
  'Savonius rotor',
  'engineer',
  'S.J. Savonius',
  'Flettner rotor ship',
  'rotating',
  'sails',
  'Wind',
  'lift',
  'Magnus effect',
  'wind power',
  'motor power',
  'rotate',
  'Flettner ship',
  'rotor',
  'axle',
  'Savonius rotor',
  'Europe',
  'Finland',
  'electrical generator',
  'starting torque',
  'wind',
  'Savonius rotor',
  'rotor design',
  'vertical-axis turbine',
  'F.M.Darrieus',
  'Darrieus rotor',
  'blades',
  'wind',
  'yawing',
  'rotates',
  'bearings',
  'torque',
  'blades',
  'power train',
  'rotor',
  'Darrieus rotor',
  'wind',
  'energy',
  'Europe',
  'Industrial Revolution',
  'wind energy',
  'electricity',
  'wind turbines',
  'wind turbines',
  'wind turbines',
  'turbine',
  'wind',
  'Yaw',
  'mechanisms',
  'yaw rotors',
  'Blades',
  'airfoil',
  'twist',
  'power output',
  'turbines',
  'wind energy',
  'environmental',
  'energy',
  'fossil fuels',
  'nuclear energy',
  'environmental',
  'energy',
  'wind power',
  'Europe',
  'Denmark',
  'Germany',
  'global warming',
  'nuclear power',
  'wind generation',
  'wind turbines',
  'kW',
  'MW',
  'machines',
  'MW',
  'installed capacity',
  'MW',
  'Europe',
  'Offshore wind energy',
  'Europe',
  'machine',
  'cost of energy',
  'wind',
  'Turkey',
  'wind energy potential',
  'wind energy',
  'Turkey',
  'electrical energy',
  'MW',
  'wind energy potential',
  'technically',
  'electricity production',
  'Turkey',
  'Marmara',
  'Ege',
  'Bozcaada',
  'Gökçeada',
  'Sinop',
  'Iskenderun',
  'wind energy potential',
  'electricity',
  'installed capacity',
  'electrical energy production',
  'wind energy',
  'Turkey',
  'MW',
  'Mw',
  'energy',
  'wind farms',
  'Çeşme',
  'wind farm',
  'Bozcaada',
  'wind energy potential',
  'installed capacity',
  'electrical energy production',
  'wind energy',
  'Turkey',
  'wind energy',
  'electrical energy production',
  'installed capacity',
  'Technical wind energy potential',
  'installed capacities',
  'Turkey',
  'Denmark',
  'Germany',
  'England',
  'Greece',
  'France',
  'Italy',
  'Spain',
  'Sweden',
  'Technical Wind Energy Potential',
  'MW',
  'Installed Capacity',
  'MW',
  'TECHNOLOGICAL',
  'WIND TURBINES',
  'Wind turbine technology',
  'technology',
  'wind turbines',
  'wind turbines',
  'aerodynamics',
  'power electronics',
  'blades',
  'Aerodynamics',
  'industry',
  'wind turbines',
  'turbines',
  'Power',
  'electronics',
  'wind turbines',
  'Power electronic',
  'turbine',
  'generator',
  'electrical network',
  'turbine',
  'energy',
  'fatigue damage',
  'network',
  'energy',
  'wind turbines',
  'cost of energy',
  'wind speeds',
  'Turbines',
  'offshore wind energy',
  'offshore',
  'wind energy',
  'electricity',
  'intermittency transmission',
  'wind turbines',
  'engineering',
  'wind turbine',
  'wind industry',
  'mechanical',
  'electrical',
  'civil engineering',
  'HORIZONTAL-AXIS WIND TURBINES',
  'wind turbine',
  'machine',
  'power',
  'wind',
  'electricity',
  'windmill',
  'machine',
  'wind',
  'power',
  'mechanical power',
  'wind turbines',
  'horizontal-',
  'vertical-axis wind turbines',
  'wind turbines',
  'horizontal-axis wind turbines',
  'HAWT',
  'axis',
  'vertical-axis wind turbine',
  'VAWT',
  'axis',
  'wind turbine',
  'aerodynamic',
  'horizontal-axis wind turbines',
  'horizontal-axis wind turbines',
  'horizontal-axis wind turbine',
  'HORIZONTAL-AXIS WIND TURBINE',
  'horizontal axis wind turbines',
  'horizontal axis wind turbine',
  'Enfield-Andreau type of horizontal axis wind turbine',
  'mechanical',
  'coupling',
  'turbine',
  'generator',
  'generator',
  'pneumatically',
  'turbine rotor',
  'blades',
  'tips',
  'centrifugal air pump',
  'horizontal-axis wind turbines',
  'tower shell',
  'highspeed air turbine',
  'generator',
  'rotor hub',
  'turbine blades',
  'blade tips',
  'Enfield-Andreau turbine',
  'drag losses',
  'flow paths',
  'bearing',
  'blade roots',
  'Enfield-Andreau turbine',
  'flow path',
  'rotors',
  'tower',
  'power',
  'rotors',
  'turbines',
  'turbines',
  'wind turbine',
  'wind turbine',
  'counter-rotating blades',
  'rotors',
  'axis',
  'rotors',
  'rotors',
  'net swept area',
  'counter-rotating blades',
  'axis',
  'net swept area',
  'wind energy conversion',
  'induced velocity',
  'theoretical maximum power coefficient',
  'rotors',
  'axis',
  'rotor',
  'Counter-rotation',
  'rotational energy',
  'wake',
  'rotor',
  'gearing',
  'concentrator',
  'wind',
  'rotor',
  'concentrator',
  'winds',
  'HORIZONTAL-AXIS WIND TURBINES',
  'horizontal-axis wind turbines',
  'horizontal-axis wind turbines',
  'wind turbine',
  'low-solidity rotor',
  'aerodynamic lift',
  'electrical generator',
  'rotating',
  'tower',
  'horizontal-axis wind turbines',
  'rotor orientation',
  'upwind',
  'downwind',
  'tower',
  'blade articulation',
  'teetering',
  'blades',
  'blades',
  'rotor control',
  'pitch',
  'stall',
  'wind',
  'free yaw',
  'active yaw',
  'upwind',
  'downwind',
  'blade coning',
  'yaw orientation',
  'upwind rotor',
  'downwind rotor',
  'rotor',
  'tower',
  'downwind turbines',
  'upwind rotors',
  'upwind',
  'downwind',
  'wind generators',
  'upwind',
  'tail vane',
  'blades',
  'wind',
  'furling mechanism',
  'blades',
  'wind stream',
  'machine',
  'winds',
  'upwind rotor',
  'downwind',
  'machines',
  'tail vane',
  'downwind',
  'tower shadow',
  'tower',
  'wind stream',
  'rotating',
  'blade',
  'tower',
  'wind speed',
  'wind',
  'rotor',
  'Upwind',
  'rigid hub',
  'three-bladed',
  'downwind',
  'teetered',
  'two-bladed turbine',
  'horizontal-axis wind turbine',
  'rotor',
  'blades',
  'hub',
  'power train',
  'rotating',
  'wind turbine',
  'rotor',
  'shafts',
  'gearbox',
  'coupling',
  'mechanical brake',
  'generator',
  'nacelle',
  'wind turbine housing',
  'bedplate',
  'yaw system',
  'tower',
  'foundation',
  'machine controls',
  'electrical system',
  'cables',
  'switchgear',
  'transformers',
  'electronic power converters',
  'horizontal-axis wind turbine',
  'upwind',
  'downwind HAWT',
  'HAWT',
  'Upwind rotor',
  'Downwind rotor',
  'ROTOR',
  'rotor',
  'hub',
  'blades',
  'wind turbine',
  'rotor',
  'single-',
  'double-',
  'three-',
  'four-bladed',
  'multi-bladed',
  'single-bladed wind rotor',
  'counter-weight',
  'blade',
  'machine',
  'twobladed rotor',
  'three-bladed rotor',
  'three-bladed rotor',
  'three-bladed rotor',
  'machine',
  'yaws',
  'wind direction',
  'two-bladed rotor',
  'tail vane',
  'yaw',
  'rotor',
  'centrifugal force',
  'tail vane',
  'wind direction',
  'two-bladed rotor',
  'centrifugal force',
  'tail vane',
  'three-bladed rotor',
  'machine',
  'centrifugal force',
  'tail vane',
  'wind turbine',
  'unconed rotor',
  'spanwise axes',
  'blades',
  'Blade axes',
  'coned rotor',
  'downwind',
  'rotor axis',
  'downwind',
  'blade',
  'aerodynamic loading',
  'upwind',
  'radial centrifugal forces',
  'Tower clearance',
  'blade tip',
  'tower',
  'blade coning',
  'rotor teetering',
  ...],
 ['JOINT IMPLEMENTATION PROJECT DESIGN DOCUMENT FORM FOR SMALL-SCALE PROJECTS',
  'Joint Implementation Supervisory Committee',
  'JOINT IMPLEMENTATION PROJECT DESIGN DOCUMENT FORM FOR SMALL-SCALE PROJECTS',
  'greenhouse gas emission reductions',
  'Environmental impacts',
  'JOINT IMPLEMENTATION PROJECT DESIGN DOCUMENT FORM FOR SMALL-SCALE PROJECTS',
  'Joint Implementation Supervisory Committee',
  'Sudenai',
  'Lendimai',
  'Wind Power',
  'Joint Implementation Project',
  'JI project',
  'wind power plants',
  'MW',
  'Sudenu',
  'Lendimu',
  'Lithuania',
  'JI Project',
  'renewable electricity',
  'wind power plants',
  'carbon intensive electricity',
  'fossil fuel',
  'power network',
  'greenhouse gas emissions',
  'pollutants',
  'fossil fuel',
  'power generation',
  'Lithuania',
  'renewable electricity',
  'Lithuania',
  'GWh',
  'electricity production',
  'wind energy',
  'MW',
  'wind power',
  'National Program of Increasing Efficiency of Energy Consumption',
  'renewable',
  'electricity',
  'wind energy',
  'biomass energy',
  'wind energy parks',
  'wind power electricity',
  'feed-in tariff',
  'kWh',
  'kWh',
  'feed-in tariff',
  'feed-in tariff',
  'wind power plant',
  'grid connection',
  'Lietuvos Energija AB',
  'electricity',
  'Transmission System Operator',
  'Lithuania',
  'feed-in tariff',
  'carbon credits',
  'Kyoto',
  'Joint Implementation scheme',
  'Electricity',
  'Renewable',
  'Energy',
  'Republic of Lithuania',
  'Republic of Lithuania',
  'Electricity',
  'State Commission for Control on Prices and Energy',
  'electricity',
  'JOINT IMPLEMENTATION PROJECT DESIGN DOCUMENT FORM FOR SMALL-SCALE PROJECTS',
  'Joint Implementation Supervisory Committee',

In [123]:
from datasets import Dataset, DatasetDict

dataset_save_path = '/data/yongchan/ATE/ACTER/huggingface/long'
os.makedirs(dataset_save_path, exist_ok=True)

dataset = DatasetDict({'train': train_dataset, 'validation': validation_dataset, 'test': test_dataset})
dataset.save_to_disk(dataset_save_path)

Saving the dataset (0/1 shards):   0%|          | 0/17 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/34 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/190 [00:00<?, ? examples/s]

# Create dataset with shorter text

In [11]:
import os
import re
import numpy as np
import pandas as pd
from collections import defaultdict
from IPython.core.debugger import set_trace

train_dataset = pd.DataFrame(columns=['text', 'label', 'unique_label'])
master_path = '/data/yongchan/ATE/ACTER/en'

def normalize_texts(texts):
    text = ' '.join(texts)
    # Remove any empty space that are placed before special characters
    text = re.sub(r'\s+(?=[\W_])', '', text)
    
    # Remove any empty space that are placed after the character /
    text = re.sub(r'/(?=\s)', '/', text)
    return text

def remove_special_characters(text):
    text = text.lower().replace(' ', '')
    return re.sub(r'[^a-zA-Z0-9\s]', '', text)

for dataset_name in os.listdir(master_path):
    rows = {}
    all_domain_terms = []
    all_candidate_words = []
    all_texts = {}
    all_term_types = []
    dataset_path = os.path.join(master_path, dataset_name, 'annotated')
    
    if dataset_name == 'cor':
        continue
    
    for category in sorted(os.listdir(dataset_path)):
        category_path = os.path.join(dataset_path, category)
        
        if category == 'annotations':
            for seq_annotation in sorted(os.listdir(category_path)):                                
                if seq_annotation == 'sequential_annotations':
                    iob_annotation_path = os.path.join(category_path, seq_annotation, 'iob_annotations', 'with_named_entities')
                    for filename in sorted(os.listdir(iob_annotation_path), key=lambda x: int(os.path.splitext(x)[0].split('_')[2])):
                        file_path = os.path.join(iob_annotation_path, filename)
                        lines = pd.read_csv(file_path,  sep='\t', na_values=[], skip_blank_lines=False, names=['word', 'boi'])
                    
                        split_indexes = lines[pd.isna(lines[['word', 'boi']]).all(axis=1)].index
                        for prev_index, split_index in zip([-1]+list(split_indexes[:-1]), split_indexes):
                            split_lines = lines.iloc[prev_index+1:split_index]
                            domain_terms = []
                            domain_term = []
                            candidate_words = []
                            for i in range(len(split_lines)):
                                candidate_word = split_lines.iloc[i]['word']                                    
                                boi = split_lines.iloc[i]['boi']
                                if candidate_word is np.nan and boi is not np.nan:
                                    candidate_word = 'None'
                                
                                if boi == 'B':
                                    if len(domain_term) == 0:
                                        domain_term.append(candidate_word)
                                    else:
                                        domain_term = normalize_texts(domain_term)
                                        domain_terms.append(domain_term)
                                        domain_term = [candidate_word]
                                elif boi == 'I':
                                    domain_term.append(candidate_word)
                                else:
                                    if len(domain_term) > 0:
                                        domain_term = normalize_texts(domain_term)
                                        domain_terms.append(domain_term)
                                        domain_term = []
                                candidate_words.append(candidate_word.lower())
                            
                            if len(domain_term) > 0:
                                domain_term = normalize_texts(domain_term)
                                domain_terms.append(domain_term)
                                                                    
                            all_domain_terms.append(domain_terms)
                            # all_candidate_words.append(candidate_words)
                            all_candidate_words.append(remove_special_characters(''.join(candidate_words)))
                            
                elif seq_annotation == 'unique_annotation_lists':
                    unique_annotation_list_path = os.path.join(category_path, seq_annotation, f"{dataset_name}_en_terms_nes.tsv")
                    lines = pd.read_csv(unique_annotation_list_path,  sep='\t', names=['word', 'term_type'])
                    for i, domain_terms in enumerate(all_domain_terms):
                        term_types = []
                        for domain_term in domain_terms:
                            domain_term = domain_term.lower()
                            term_type = ''
                            count = 0
                            while len(term_type) == 0:                                    
                                if count==0:
                                    term_type = lines[lines['word']==domain_term]['term_type']
                                
                                elif count==1:
                                    character_removed_domain_term_wo_ws = re.sub(r'[^a-zA-Z0-9\s]', '', domain_term)
                                    term_type = lines[lines['word']==character_removed_domain_term_wo_ws]['term_type']
                                    
                                elif count==2:
                                    character_removed_domain_term_w_ws = re.sub(r'[^a-zA-Z0-9\s]', ' ', domain_term).split(' ')
                                    for i in sorted(range(len(character_removed_domain_term_w_ws)), reverse=True):
                                        for j in range(len(character_removed_domain_term_w_ws)):
                                            sliced_dash_removed_domain_term_w_ws = ' '.join(character_removed_domain_term_w_ws[j:j+i])
                                            term_type = lines[lines['word'].str.contains(sliced_dash_removed_domain_term_w_ws)]['term_type']
                                            if len(term_type) > 0:
                                                break
                                        if len(term_type) > 0:
                                            break
                                
                                elif count > 2:
                                    term_type = 'Not Annotated'                                            
                                    print(f'Path: {unique_annotation_list_path}, domain_term: {domain_term}, index: {i}')
                                    break
                                    
                                count += 1                                    

                            if not isinstance(term_type, str):
                                term_type = term_type.astype(str).values[0]
                            term_types.append(term_type)
                        all_term_types.append(term_types)
        
        # TODO: 여기 고치기...
        elif category == 'texts':
            i =0
            for filename in sorted(os.listdir(category_path), key=lambda x: int(os.path.splitext(x)[0].split('_')[2])):
                print(f'###### Filename: {filename} is processing... #######')
                with open(os.path.join(category_path, filename), 'r') as f:
                    text = f.read()
                    texts = text.split('\n')                            
                    texts_copy = texts.copy()
                    for text_idx in range(len(texts)):
                        while '\n' in texts[text_idx]:
                            texts[text_idx] = texts[text_idx].replace('\n', '')
                    
                    while '' in texts:
                        texts.remove('')
                        
                    modified_texts = list(map(remove_special_characters, texts))
                    modified_texts_to_texts={modified_text: text for modified_text, text in zip(modified_texts, texts)}
                    temp_all_texts = []
                    temp_all_domain_terms = []
                    temp_all_term_types = []
                    j=0
                    while i < len(all_candidate_words):
                        all_candidate_word = all_candidate_words[i]
                        # if j==286 and filename == 'wind_en_02.txt':
                        #     print('idk')
                        for idx, modified_text in enumerate(modified_texts[j:]):
                            if all_candidate_word in modified_text:
                                temp_all_texts.append(modified_text)
                                domain_term = all_domain_terms[i]
                                temp_all_domain_terms.append(domain_term)
                                term_types = all_term_types[i]
                                temp_all_term_types.append(term_types)
                                if all_candidate_word == modified_text:
                                    j+=1
                                elif i < len(all_candidate_words)-1 and all_candidate_words[i+1] not in modified_text:
                                    j+=1
                                break
                            elif len(modified_text[j:]) <= 1:
                                j+=1
                        
                        i+=1
                        if len(modified_texts[j:]) == 0 or idx == len(modified_texts[j:]) and modified_texts[j:][-1] == all_candidate_word:
                            for modified_text, domain_terms, term_types in zip(temp_all_texts, temp_all_domain_terms, temp_all_term_types):
                                text = modified_texts_to_texts[modified_text]
                                if text not in all_texts:
                                    all_texts[text] = [[],[]]
                                all_texts[text][0].extend(domain_terms)
                                all_texts[text][1].extend(term_types)
                            for text in texts:
                                if text not in list(all_texts.keys()):
                                    print(f'Text: {text} is not in all_texts')
                            print(f'###### Filename: {filename} is finished! #######\n')
                            break
                        
            # if len_texts != len(all_texts):
            #     raise ValueError(f'Length of texts: {len_texts} is not equal to length of all_texts: {len(all_texts)}')
    
    all_text_values = all_texts.values()
    all_domain_terms, all_term_types = [], []
    for all_text_value in all_text_values:
        all_domain_terms.append(all_text_value[0])
        all_term_types.append(all_text_value[1])
        
    rows = {'text': list(all_texts.keys()), 'label': all_domain_terms, 'unique_label': all_term_types}
    rows['dataset_name'] = [dataset_name]*len(all_texts)
    if dataset_name == 'htfl':
        rows['domain'] = ['Heart Failure']*len(all_texts)
        test_dataset = pd.DataFrame(rows)
    elif dataset_name == 'equi':
        rows['domain'] = ['Equitation']*len(all_texts)
        validation_dataset = pd.DataFrame(rows)
    else:
        dataset_name_to_domain = {'corp': 'Corruption', 'wind': 'Wind Energy'}
        rows['domain'] = [dataset_name_to_domain[dataset_name]]*len(all_texts)
        dataset_name_to_domain = {'corp': 'Corruption', 'wind': 'Wind Energy'}
        train_dataset = pd.concat([train_dataset, pd.DataFrame(rows)])

###### Filename: wind_en_01.txt is processing... #######
Text: : is not in all_texts
Text: x is not in all_texts
Text: λ = 10 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . is not in all_texts
Text: CP is not in all_texts
Text: P is not in all_texts
Text: w′ is not in all_texts
Text: T is not in all_texts
Text: B is not in all_texts
Text: a is not in all_texts
Text: λ is not in all_texts
Text: λd λr is not in all_texts
Text: ci is not in all_texts
Text: ρ is not in all_texts
Text: Ω is not in all_texts
Text: α is not in all_texts
Text: θ is not in all_texts
Text: θi is not in all_texts
Text: ϕ is not in all_texts
Text: σ ν is not in all_texts
Text: γ Γ is not in all_texts
Text: δΓ is not in all_texts
Text: Re is not in all_texts
Text: 6 is not in all_texts
Text: 12 is not in all_texts
Text: (a) is not in all_texts
Text: (a) is not in all_texts
Text: λ= is not in all_texts
Text: CT = is not in all_texts
Text: a= is not in all_texts
Text: P= is not in all_texts
Text: λ is not in all_texts
Text: λ is not in all_texts
Text: r is not in all_texts
Text: a is not in all_texts
Text: λ is not in all_texts
Text: U ∞ (1 - a ) sin(ϕ ) is not in all_texts
Text: σ= is not in all_texts
Text: (3.4.5) is not in all_texts
Text: a= is not in all_texts
Text: R is not in all_texts
Text: R is not in all_texts
Text: R is not in all_texts
Text: λ is not in all_texts
Text: λ is not in all_texts
Text: λ is not in all_texts
Text: CT = is not in all_texts
Text: λ is not in all_texts
Text: a= is not in all_texts
Text: λ is not in all_texts
Text: CTr = is not in all_texts
Text: ϕopt is not in all_texts
Text: When CTr < 0.96 is not in all_texts
Text: If differences > 0.01 is not in all_texts
Text: 89 is not in all_texts
###### Filename: wind_en_01.txt is finished! #######

###### Filename: wind_en_02.txt is processing... #######
Text: 1 is not in all_texts
Text: & is not in all_texts
Text: " is not in all_texts
Text: 7 is not in all_texts
Text: • is not in all_texts
Text: • is not in all_texts
Text: • is not in all_texts
Text: • • is not in all_texts
Text: • is not in all_texts
Text: • • is not in all_texts
###### Filename: wind_en_02.txt is finished! #######

###### Filename: wind_en_04.txt is processing... #######
Text: Conference Paper is not in all_texts
Text: 1 is not in all_texts
Text: Support Structures is not in all_texts
###### Filename: wind_en_04.txt is finished! #######

###### Filename: wind_en_26.txt is processing... #######
###### Filename: wind_en_26.txt is finished! #######

###### Filename: wind_en_32.txt is processing... #######
###### Filename: wind_en_32.txt is finished! #######

###### Filename: htfl_en_001.txt is processing... #######
###### Filename: htfl_en_001.txt is finished! #######

###### Filename: htfl_en_002.txt is processing... #######
###### Filename: htfl_en_002.txt is finished! #######

###### Filename: htfl_en_003.txt is processing... #######
###### Filename: htfl_en_003.txt is finished! #######

###### Filename: htfl_en_004.txt is processing... #######
###### Filename: htfl_en_004.txt is finished! #######

###### Filename: htfl_en_005.txt is processing... #######
###### Filename: htfl_en_005.txt is finished! #######

###### Filename: htfl_en_006.txt is processing... #######
###### Filename: htfl_en_006.txt is finished! #######

###### Filename: htfl_en_007.txt is processing... #######
###### Filename: htfl_en_007.txt is finished! #######

###### Filename: htfl_en_008.txt is processing... #######
###### Filename: htfl_en_008.txt is finished! #######

###### Filename: htfl_en_009.txt is processing... #######
Text: MAIN OUTCOMES AND MEASURES: is not in all_texts
Text: Coprimary end points included 72-hour cumulative urine volume (decongestion end point) and the change in serum cystatin C from enrollment to 72 hours (renal function end point). is not in all_texts
###### Filename: htfl_en_009.txt is finished! #######

###### Filename: htfl_en_010.txt is processing... #######
###### Filename: htfl_en_010.txt is finished! #######

###### Filename: htfl_en_011.txt is processing... #######
###### Filename: htfl_en_011.txt is finished! #######

###### Filename: htfl_en_012.txt is processing... #######
###### Filename: htfl_en_012.txt is finished! #######

###### Filename: htfl_en_013.txt is processing... #######
###### Filename: htfl_en_013.txt is finished! #######

###### Filename: htfl_en_014.txt is processing... #######
###### Filename: htfl_en_014.txt is finished! #######

###### Filename: htfl_en_015.txt is processing... #######
###### Filename: htfl_en_015.txt is finished! #######

###### Filename: htfl_en_016.txt is processing... #######
###### Filename: htfl_en_016.txt is finished! #######

###### Filename: htfl_en_017.txt is processing... #######
###### Filename: htfl_en_017.txt is finished! #######

###### Filename: htfl_en_018.txt is processing... #######
###### Filename: htfl_en_018.txt is finished! #######

###### Filename: htfl_en_019.txt is processing... #######
###### Filename: htfl_en_019.txt is finished! #######

###### Filename: htfl_en_020.txt is processing... #######
###### Filename: htfl_en_020.txt is finished! #######

###### Filename: htfl_en_021.txt is processing... #######
###### Filename: htfl_en_021.txt is finished! #######

###### Filename: htfl_en_022.txt is processing... #######
###### Filename: htfl_en_022.txt is finished! #######

###### Filename: htfl_en_023.txt is processing... #######
###### Filename: htfl_en_023.txt is finished! #######

###### Filename: htfl_en_024.txt is processing... #######
###### Filename: htfl_en_024.txt is finished! #######

###### Filename: htfl_en_025.txt is processing... #######
###### Filename: htfl_en_025.txt is finished! #######

###### Filename: htfl_en_026.txt is processing... #######
###### Filename: htfl_en_026.txt is finished! #######

###### Filename: htfl_en_027.txt is processing... #######
###### Filename: htfl_en_027.txt is finished! #######

###### Filename: htfl_en_028.txt is processing... #######
###### Filename: htfl_en_028.txt is finished! #######

###### Filename: htfl_en_029.txt is processing... #######
###### Filename: htfl_en_029.txt is finished! #######

###### Filename: htfl_en_030.txt is processing... #######
###### Filename: htfl_en_030.txt is finished! #######

###### Filename: htfl_en_031.txt is processing... #######
###### Filename: htfl_en_031.txt is finished! #######

###### Filename: htfl_en_032.txt is processing... #######
###### Filename: htfl_en_032.txt is finished! #######

###### Filename: htfl_en_033.txt is processing... #######
###### Filename: htfl_en_033.txt is finished! #######

###### Filename: htfl_en_034.txt is processing... #######
###### Filename: htfl_en_034.txt is finished! #######

###### Filename: htfl_en_035.txt is processing... #######
###### Filename: htfl_en_035.txt is finished! #######

###### Filename: htfl_en_036.txt is processing... #######
###### Filename: htfl_en_036.txt is finished! #######

###### Filename: htfl_en_037.txt is processing... #######
###### Filename: htfl_en_037.txt is finished! #######

###### Filename: htfl_en_038.txt is processing... #######
###### Filename: htfl_en_038.txt is finished! #######

###### Filename: htfl_en_039.txt is processing... #######
###### Filename: htfl_en_039.txt is finished! #######

###### Filename: htfl_en_040.txt is processing... #######
###### Filename: htfl_en_040.txt is finished! #######

###### Filename: htfl_en_041.txt is processing... #######
###### Filename: htfl_en_041.txt is finished! #######

###### Filename: htfl_en_042.txt is processing... #######
###### Filename: htfl_en_042.txt is finished! #######

###### Filename: htfl_en_043.txt is processing... #######
###### Filename: htfl_en_043.txt is finished! #######

###### Filename: htfl_en_044.txt is processing... #######
###### Filename: htfl_en_044.txt is finished! #######

###### Filename: htfl_en_045.txt is processing... #######
###### Filename: htfl_en_045.txt is finished! #######

###### Filename: htfl_en_046.txt is processing... #######
###### Filename: htfl_en_046.txt is finished! #######

###### Filename: htfl_en_047.txt is processing... #######
###### Filename: htfl_en_047.txt is finished! #######

###### Filename: htfl_en_048.txt is processing... #######
###### Filename: htfl_en_048.txt is finished! #######

###### Filename: htfl_en_049.txt is processing... #######
###### Filename: htfl_en_049.txt is finished! #######

###### Filename: htfl_en_050.txt is processing... #######
###### Filename: htfl_en_050.txt is finished! #######

###### Filename: htfl_en_051.txt is processing... #######
###### Filename: htfl_en_051.txt is finished! #######

###### Filename: htfl_en_052.txt is processing... #######
###### Filename: htfl_en_052.txt is finished! #######

###### Filename: htfl_en_053.txt is processing... #######
###### Filename: htfl_en_053.txt is finished! #######

###### Filename: htfl_en_054.txt is processing... #######
###### Filename: htfl_en_054.txt is finished! #######

###### Filename: htfl_en_055.txt is processing... #######
###### Filename: htfl_en_055.txt is finished! #######

###### Filename: htfl_en_056.txt is processing... #######
###### Filename: htfl_en_056.txt is finished! #######

###### Filename: htfl_en_057.txt is processing... #######
###### Filename: htfl_en_057.txt is finished! #######

###### Filename: htfl_en_058.txt is processing... #######
###### Filename: htfl_en_058.txt is finished! #######

###### Filename: htfl_en_059.txt is processing... #######
###### Filename: htfl_en_059.txt is finished! #######

###### Filename: htfl_en_060.txt is processing... #######
###### Filename: htfl_en_060.txt is finished! #######

###### Filename: htfl_en_061.txt is processing... #######
###### Filename: htfl_en_061.txt is finished! #######

###### Filename: htfl_en_062.txt is processing... #######
###### Filename: htfl_en_062.txt is finished! #######

###### Filename: htfl_en_063.txt is processing... #######
###### Filename: htfl_en_063.txt is finished! #######

###### Filename: htfl_en_064.txt is processing... #######
###### Filename: htfl_en_064.txt is finished! #######

###### Filename: htfl_en_065.txt is processing... #######
###### Filename: htfl_en_065.txt is finished! #######

###### Filename: htfl_en_066.txt is processing... #######
###### Filename: htfl_en_066.txt is finished! #######

###### Filename: htfl_en_067.txt is processing... #######
###### Filename: htfl_en_067.txt is finished! #######

###### Filename: htfl_en_068.txt is processing... #######
###### Filename: htfl_en_068.txt is finished! #######

###### Filename: htfl_en_069.txt is processing... #######
###### Filename: htfl_en_069.txt is finished! #######

###### Filename: htfl_en_070.txt is processing... #######
###### Filename: htfl_en_070.txt is finished! #######

###### Filename: htfl_en_071.txt is processing... #######
###### Filename: htfl_en_071.txt is finished! #######

###### Filename: htfl_en_072.txt is processing... #######
###### Filename: htfl_en_072.txt is finished! #######

###### Filename: htfl_en_073.txt is processing... #######
###### Filename: htfl_en_073.txt is finished! #######

###### Filename: htfl_en_074.txt is processing... #######
###### Filename: htfl_en_074.txt is finished! #######

###### Filename: htfl_en_075.txt is processing... #######
###### Filename: htfl_en_075.txt is finished! #######

###### Filename: htfl_en_076.txt is processing... #######
###### Filename: htfl_en_076.txt is finished! #######

###### Filename: htfl_en_077.txt is processing... #######
###### Filename: htfl_en_077.txt is finished! #######

###### Filename: htfl_en_078.txt is processing... #######
###### Filename: htfl_en_078.txt is finished! #######

###### Filename: htfl_en_079.txt is processing... #######
###### Filename: htfl_en_079.txt is finished! #######

###### Filename: htfl_en_080.txt is processing... #######
###### Filename: htfl_en_080.txt is finished! #######

###### Filename: htfl_en_081.txt is processing... #######
###### Filename: htfl_en_081.txt is finished! #######

###### Filename: htfl_en_082.txt is processing... #######
###### Filename: htfl_en_082.txt is finished! #######

###### Filename: htfl_en_083.txt is processing... #######
###### Filename: htfl_en_083.txt is finished! #######

###### Filename: htfl_en_084.txt is processing... #######
###### Filename: htfl_en_084.txt is finished! #######

###### Filename: htfl_en_085.txt is processing... #######
###### Filename: htfl_en_085.txt is finished! #######

###### Filename: htfl_en_086.txt is processing... #######
###### Filename: htfl_en_086.txt is finished! #######

###### Filename: htfl_en_087.txt is processing... #######
###### Filename: htfl_en_087.txt is finished! #######

###### Filename: htfl_en_088.txt is processing... #######
###### Filename: htfl_en_088.txt is finished! #######

###### Filename: htfl_en_089.txt is processing... #######
###### Filename: htfl_en_089.txt is finished! #######

###### Filename: htfl_en_090.txt is processing... #######
###### Filename: htfl_en_090.txt is finished! #######

###### Filename: htfl_en_091.txt is processing... #######
###### Filename: htfl_en_091.txt is finished! #######

###### Filename: htfl_en_092.txt is processing... #######
###### Filename: htfl_en_092.txt is finished! #######

###### Filename: htfl_en_093.txt is processing... #######
###### Filename: htfl_en_093.txt is finished! #######

###### Filename: htfl_en_094.txt is processing... #######
###### Filename: htfl_en_094.txt is finished! #######

###### Filename: htfl_en_095.txt is processing... #######
###### Filename: htfl_en_095.txt is finished! #######

###### Filename: htfl_en_096.txt is processing... #######
###### Filename: htfl_en_096.txt is finished! #######

###### Filename: htfl_en_097.txt is processing... #######
###### Filename: htfl_en_097.txt is finished! #######

###### Filename: htfl_en_098.txt is processing... #######
###### Filename: htfl_en_098.txt is finished! #######

###### Filename: htfl_en_099.txt is processing... #######
###### Filename: htfl_en_099.txt is finished! #######

###### Filename: htfl_en_100.txt is processing... #######
###### Filename: htfl_en_100.txt is finished! #######

###### Filename: htfl_en_101.txt is processing... #######
###### Filename: htfl_en_101.txt is finished! #######

###### Filename: htfl_en_102.txt is processing... #######
###### Filename: htfl_en_102.txt is finished! #######

###### Filename: htfl_en_103.txt is processing... #######
###### Filename: htfl_en_103.txt is finished! #######

###### Filename: htfl_en_104.txt is processing... #######
###### Filename: htfl_en_104.txt is finished! #######

###### Filename: htfl_en_105.txt is processing... #######
###### Filename: htfl_en_105.txt is finished! #######

###### Filename: htfl_en_106.txt is processing... #######
###### Filename: htfl_en_106.txt is finished! #######

###### Filename: htfl_en_107.txt is processing... #######
###### Filename: htfl_en_107.txt is finished! #######

###### Filename: htfl_en_108.txt is processing... #######
###### Filename: htfl_en_108.txt is finished! #######

###### Filename: htfl_en_109.txt is processing... #######
###### Filename: htfl_en_109.txt is finished! #######

###### Filename: htfl_en_110.txt is processing... #######
###### Filename: htfl_en_110.txt is finished! #######

###### Filename: htfl_en_111.txt is processing... #######
###### Filename: htfl_en_111.txt is finished! #######

###### Filename: htfl_en_112.txt is processing... #######
###### Filename: htfl_en_112.txt is finished! #######

###### Filename: htfl_en_113.txt is processing... #######
###### Filename: htfl_en_113.txt is finished! #######

###### Filename: htfl_en_114.txt is processing... #######
###### Filename: htfl_en_114.txt is finished! #######

###### Filename: htfl_en_115.txt is processing... #######
###### Filename: htfl_en_115.txt is finished! #######

###### Filename: htfl_en_116.txt is processing... #######
###### Filename: htfl_en_116.txt is finished! #######

###### Filename: htfl_en_117.txt is processing... #######
###### Filename: htfl_en_117.txt is finished! #######

###### Filename: htfl_en_118.txt is processing... #######
###### Filename: htfl_en_118.txt is finished! #######

###### Filename: htfl_en_119.txt is processing... #######
###### Filename: htfl_en_119.txt is finished! #######

###### Filename: htfl_en_120.txt is processing... #######
###### Filename: htfl_en_120.txt is finished! #######

###### Filename: htfl_en_121.txt is processing... #######
###### Filename: htfl_en_121.txt is finished! #######

###### Filename: htfl_en_122.txt is processing... #######
###### Filename: htfl_en_122.txt is finished! #######

###### Filename: htfl_en_123.txt is processing... #######
###### Filename: htfl_en_123.txt is finished! #######

###### Filename: htfl_en_124.txt is processing... #######
###### Filename: htfl_en_124.txt is finished! #######

###### Filename: htfl_en_125.txt is processing... #######
###### Filename: htfl_en_125.txt is finished! #######

###### Filename: htfl_en_126.txt is processing... #######
###### Filename: htfl_en_126.txt is finished! #######

###### Filename: htfl_en_127.txt is processing... #######
###### Filename: htfl_en_127.txt is finished! #######

###### Filename: htfl_en_128.txt is processing... #######
###### Filename: htfl_en_128.txt is finished! #######

###### Filename: htfl_en_129.txt is processing... #######
###### Filename: htfl_en_129.txt is finished! #######

###### Filename: htfl_en_130.txt is processing... #######
###### Filename: htfl_en_130.txt is finished! #######

###### Filename: htfl_en_131.txt is processing... #######
###### Filename: htfl_en_131.txt is finished! #######

###### Filename: htfl_en_132.txt is processing... #######
###### Filename: htfl_en_132.txt is finished! #######

###### Filename: htfl_en_133.txt is processing... #######
###### Filename: htfl_en_133.txt is finished! #######

###### Filename: htfl_en_134.txt is processing... #######
###### Filename: htfl_en_134.txt is finished! #######

###### Filename: htfl_en_135.txt is processing... #######
###### Filename: htfl_en_135.txt is finished! #######

###### Filename: htfl_en_136.txt is processing... #######
###### Filename: htfl_en_136.txt is finished! #######

###### Filename: htfl_en_137.txt is processing... #######
###### Filename: htfl_en_137.txt is finished! #######

###### Filename: htfl_en_138.txt is processing... #######
###### Filename: htfl_en_138.txt is finished! #######

###### Filename: htfl_en_139.txt is processing... #######
###### Filename: htfl_en_139.txt is finished! #######

###### Filename: htfl_en_140.txt is processing... #######
###### Filename: htfl_en_140.txt is finished! #######

###### Filename: htfl_en_141.txt is processing... #######
###### Filename: htfl_en_141.txt is finished! #######

###### Filename: htfl_en_142.txt is processing... #######
###### Filename: htfl_en_142.txt is finished! #######

###### Filename: htfl_en_143.txt is processing... #######
###### Filename: htfl_en_143.txt is finished! #######

###### Filename: htfl_en_144.txt is processing... #######
###### Filename: htfl_en_144.txt is finished! #######

###### Filename: htfl_en_145.txt is processing... #######
###### Filename: htfl_en_145.txt is finished! #######

###### Filename: htfl_en_146.txt is processing... #######
###### Filename: htfl_en_146.txt is finished! #######

###### Filename: htfl_en_147.txt is processing... #######
###### Filename: htfl_en_147.txt is finished! #######

###### Filename: htfl_en_148.txt is processing... #######
###### Filename: htfl_en_148.txt is finished! #######

###### Filename: htfl_en_149.txt is processing... #######
###### Filename: htfl_en_149.txt is finished! #######

###### Filename: htfl_en_150.txt is processing... #######
###### Filename: htfl_en_150.txt is finished! #######

###### Filename: htfl_en_151.txt is processing... #######
###### Filename: htfl_en_151.txt is finished! #######


In [13]:
print(f'Train dataset length: {len(train_dataset)}')
print(f'Validation dataset length: {len(validation_dataset)}')
print(f'Test dataset length: {len(test_dataset)}')

Train dataset length: 2326
Validation dataset length: 586
Test dataset length: 754

In [14]:
pd.set_option('display.max_colwidth', 500)
test_dataset.tail(10)

,text,label,unique_label,dataset_name,domain
744,The HeartMate 3 left ventricular assist system (LVAS) is intended to provide long-term support to patients with advanced heart failure. The centrifugal flow pump is designed for enhanced hemocompatibility by incorporating a magnetically levitated rotor with wide blood-flow paths and an artificial pulse.,"[HeartMate, left ventricular assist system, LVAS, patients, heart failure, centrifugal flow pump, hemocompatibility, blood-flow, pulse]","[Named_Entity, Specific_Term, Specific_Term, Common_Term, Common_Term, Specific_Term, Specific_Term, Common_Term, Common_Term]",htfl,Heart Failure
745,"The aim of this single-arm, prospective, multicenter study was to evaluate the performance and safety of this LVAS.","[prospective, LVAS]","[Specific_Term, Specific_Term]",htfl,Heart Failure
746,"The primary endpoint was 6-month survival compared with INTERMACS (Interagency Registry for Mechanically Assisted Circulatory Support)-derived performance goal. Patients were adults with ejection fraction ≤ 25%, cardiac index ≤ 2.2 l/min/m(2) without inotropes or were inotrope-dependent on optimal medical management, or listed for transplant.","[primary endpoint, INTERMACS, Interagency Registry for Mechanically Assisted Circulatory Support)-derived, Patients, ejection fraction, cardiac index, inotropes, medical, transplant]","[Specific_Term, Named_Entity, Specific_Term, Common_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term, Common_Term]",htfl,Heart Failure
747,"Fifty patients were enrolled at 10 centers. The indications for LVAS support were bridge to transplantation (54%) or destination therapy (46%). At 6 months, 88% of patients continued on support, 4% received transplants, and 8% died. Thirty-day mortality was 2% and 6-month survival 92%, which exceeded the 88% performance goal. Support with the fully magnetically levitated LVAS significantly reduced mortality risk by 66% compared with the Seattle Heart Failure Model-predicted survival of 78% (...","[patients, LVAS, bridge to transplantation, destination therapy, patients, transplants, mortality, fully magnetically levitated LVAS, significantly, mortality, Seattle Heart Failure Model-predicted, p, adverse events, reoperation, bleeding, driveline, infection, gastrointestinal bleeding, stroke, Rankin Score, pump thrombosis, hemolysis, New York Heart Association classification, 6-min walk test, quality-of-life]","[Common_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term, Common_Term, Common_Term, Specific_Term, OOD_Term, Common_Term, Named_Entity, OOD_Term, Specific_Term, Common_Term, Common_Term, Specific_Term, Common_Term, Specific_Term, Common_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Specific_Term, Common_Term]",htfl,Heart Failure
748,"The results show that the fully magnetically levitated centrifugal-flow chronic LVAS is safe, with high 30-day and 6-month survival rates, a favorable adverse event profile, and improved quality of life and functional status.","[fully magnetically levitated centrifugal-flow chronic LVAS, adverse event, quality of life, functional status]","[Specific_Term, Specific_Term, Common_Term, Specific_Term]",htfl,Heart Failure
749,Tools for Economic Analysis of Patient Management Interventions in Heart Failure Cost-Effectiveness Model: A Web-based program designed to evaluate the cost-effectiveness of disease management programs in heart failure.,"[Tools for Economic Analysis of Patient Management Interventions in Heart Failure Cost-Effectiveness Model, disease, heart failure]","[Named_Entity, Common_Term, Common_Term]",htfl,Heart Failure
750,"Heart failure disease management programs can influence medical resource use and quality-adjusted survival. Because projecting long-term costs and survival is challenging, a consistent and valid approach to extrapolating short-term outcomes would be valuable.","[Heart failure, disease, medical, outcomes]","[Common_Term, Common_Term, Common_Term, Common_Term]",htfl,Heart Failure
751,"We developed the Tools for Economic Analysis of Patient Management Interventions in Heart Failure Cost-Effectiveness Model, a Web-based simulation tool designed to integrate data on demographic, clinical, and laboratory characteristics; use of evidence-based medications; and costs to generate predicted outcomes. Survival projections are based on a modified Seattle Heart Failure Model. Projections of resource use and quality of life are modeled using relationships with time-varying Seattle He...","[Tools for Economic Analysis of Patient Management Interventions in Heart Failure Cost-Effectiveness Model, clinical, evidence-based, medications, outcomes, Seattle Heart Failure Model, quality of life, Seattle Heart Failure Model, single-cohort study]","[Named_Entity, Common_Term, Specific_Term, Common_Term, Common_Term, Named_Entity, Common_Term, Named_Entity, OOD_Term]",htfl,Heart Failure
752,"The model demonstrated acceptable internal and external validity in replicating resource use, costs, and survival estimates from 3 clinical trials. Simulations to evaluate the cost-effectiveness of heart failure disease management programs across 3 scenarios demonstrate how the model can be used to design a program in which short-term improvements in functioning and use of evidence-based treatments are sufficient to demonstrate good long-term value to the health care system.","[clinical, heart failure, disease, evidence-based, health care]","[Common_Term, Common_Term, Common_Term, Specific_Term, Common_Term]",htfl,Heart Failure
753,The Tools for Economic Analysis of Patient Management Interventions in Heart Failure Cost-Effectiveness Model provides researchers and providers with a tool for conducting long-term cost-effectiveness analyses of disease management programs in heart failure.,"[Tools for Economic Analysis of Patient Management Interventions in Heart Failure Cost-Effectiveness Model, disease, heart failure]","[Named_Entity, Common_Term, Common_Term]",htfl,Heart Failure

In [15]:
train_dataset.tail(10)

,text,label,unique_label,dataset_name,domain
1012,The additional division in sub-objectives is done to facilitate the calculation of the breakdown of estimated impact on expenditure in section 3.2.,[expenditure],[Common_Term],corp,Corruption
1013,DA= Differentiated appropriations / DNA= Non-Differentiated Appropriations,"[appropriations, Appropriations]","[Specific_Term, Specific_Term]",corp,Corruption
1014,EFTA: European Free Trade Association.,"[EFTA, European Free Trade Association]","[Named_Entity, Named_Entity]",corp,Corruption
1015,"Candidate countries and, where applicable, potential candidate countries from the Western Balkans.",[Balkans],[Named_Entity],corp,Corruption
1016,"Technical and/or administrative assistance and expenditure in support of the implementation of EU programmes and/or actions (former ""BA"" lines), indirect research, direct research.","[administrative, expenditure, EU, administrative, expenditure, EU]","[Common_Term, Common_Term, Named_Entity, Common_Term, Common_Term, Named_Entity]",corp,Corruption
1017,"Outputs are products and services to be supplied (e.g.: number of student exchanges financed, number of km of roads built, etc.).",[financed],[Common_Term],corp,Corruption
1018,"Through targeted calls for proposals within the EU programme for prevention and fight against crime (call targeting financial and economic crime), civil society organisations will be encouraged to apply for subject specific assessments of Member States' anti-corruption efforts. The exact number and specific target of each contract cannot be predicted at this point.","[EU, crime, financial, economic crime, civil society, anti-corruption, contract]","[Named_Entity, Common_Term, Common_Term, Common_Term, Common_Term, Common_Term, Common_Term]",corp,Corruption
1019,Public procurement procedures. The contractor will be tasked to set up the network of 27 local research correspondents and cover the coordination/logistic aspects.,"[Public procurement procedures, contractor]","[Common_Term, Common_Term]",corp,Corruption
1020,"The decision to set up such programme and the details of its functioning may only be taken/clarified at a later stage, once the preparations for the first Report are more advanced. One possibility for its setting up would be via procurement procedures (i.e. a contractor tasked to organise a number of roughly 5 experience-sharing workshops/events per year). The costs were estimated for approximately 50 participants + 5 speakers, with 1,000 Euros cost/person and an overall 100,000 Euros for or...","[procurement procedures, contractor, costs, cost]","[Common_Term, Common_Term, Common_Term, Common_Term]",corp,Corruption
1021,"CA= Contract Agent; INT= agency staff ("" Intérimaire"") ; JED= "" Jeune Expert en Délégation"" (Young Experts in Delegations); LA= Local Agent; SNE= Seconded National Expert;",[Contract],[Common_Term],corp,Corruption

In [128]:
from datasets import Dataset, DatasetDict

train_dataset = Dataset.from_pandas(train_dataset, preserve_index=False)
test_dataset = Dataset.from_pandas(test_dataset, preserve_index=False)
validation_dataset = Dataset.from_pandas(validation_dataset, preserve_index=False)

In [129]:
from datasets import Dataset, DatasetDict

dataset_save_path = '/data/yongchan/ATE/ACTER/huggingface/short'
os.makedirs(dataset_save_path, exist_ok=True)

dataset = DatasetDict({'train': train_dataset, 'validation': validation_dataset, 'test': test_dataset})
dataset.save_to_disk(dataset_save_path)

Saving the dataset (0/1 shards):   0%|          | 0/2326 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/586 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/754 [00:00<?, ? examples/s]